//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mocktestEntities1 : DbContext
    {
        public mocktestEntities1()
            : base("name=mocktestEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OptionDetail> OptionDetails { get; set; }
        public virtual DbSet<QuesDetail> QuesDetails { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ScoreDetail> ScoreDetails { get; set; }
        public virtual DbSet<SubTopic> SubTopics { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
