//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.ScoreDetails = new HashSet<ScoreDetail>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public int roleId { get; set; }
        public string RollNo { get; set; }
        public string Branch { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<ScoreDetail> ScoreDetails { get; set; }
    }
}
